version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Run production build
          command: CI=false npm run build   # CI=false here so react-scripts does not treat warnings as errors
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
